### PR TITLE
Set up CPack packaging and allowed to disable building of tests.

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by Breigner01** [comment]
Can you explain why you are doing this?
On my end I don't see why it should be added to the project as it is easy to build and as it is C++ it is the easiest way to do it as it is a really small project like that. It would make much more sense on a bigger project as here you don't even need to use the cmakelist included you could just use the header made for the lib.

**Comment by KOLANICH** [comment]
>Can you explain why you are doing this?

>On my end I don't see why it should be added to the project as it is easy to build and as it is C++ it is the easiest way to do it as it is a really small project like that.

Because it is a library that can be used into multiple projects. It is much easier to create a package (for rust there exists cargo, for python there exists pip, but for C there are multiple package managers: apt/deb, dnf/rpm and pakman) and install it into the system once than to use git submodules for each project and keeping them actual.

**Comment by Breigner01** [comment]
First yeah python and other languages have package managers for their libraries but it is not meant to be this way for C/C++. Furthermore pacman, dnf and apt aren't C/C++ package manager, they are Linux distributions package manager which can most of the time install C/C++ most known libraries.
As it isn't a widely used library it doesn't make sense to try and use an unofficial package manager that is meant for C/C++ as it isn't meant to be used this way.
If you want to use a C/C++ library you'd rather select the version of it manually than let it update by itself because for a project if on a version it builds with let's say before C++11 (because of abi changes and stuff) and on other versions it breaks before C++11 and works with newer versions well depending on your needs you'd rather include it by yourself in your project.

**Comment by KOLANICH** [comment]
>but it is not meant to be this way for C/C++.
>Furthermore pacman, dnf and apt aren't C/C++ package manager, they are Linux distributions package manager which can most of the time install C/C++ most known libraries.

It maybe is not meant by C++ commitee, but it is exactly the way it is used in distros. One can even say it is a de-facto standard for C++ to use a distro package manager. And it works quite well, so there were attempts to clone that model to create a "package manager for C++", such as conan and nix and vcpkg. Of course it has resulted only in that there is a yet another package managers one has to support.

>If you want to use a C/C++ library you'd rather select the version of it manually than let it update by itself because for a project if on a version it builds with let's say before C++11 (because of abi changes and stuff) and on other versions it breaks before C++11 and works with newer versions well depending on your needs you'd rather include it by yourself in your project.

I absolutely dislike this approach. For me it would be a lot more convenient if it was a package for a latest version of a library for each distro package manager, and that that library can be discovered by standard mechanisms. Then to let the distro package manager update it. Then if build fails because if API incompatibility,  that means that my code is not compatible with the latest version of its dependencies,  and it means that there is an issue in my code, becuse the general rule is that a user of each software must be able to update its dependencies himself, getting the features and bugfixes present in newer versions of the dependency, if he needs them, not being stuck to older version because someone has used it as a submodule somewhere or just copied as files.

**Comment by Breigner01** [comment]
Don't forget that it is a single header here and you think of development as development that you do on your own but there are a lot of cases (in enterprises) where they use older versions because updating the whole project (most of the times few 100k of lines of even more and updating everything isn't wanted by them which is why in C/C++ as Linux distribution package manager don't allow to install a specific version it might be better to have the lib in your project directly and you can make it so that cmake fetches a version (a git tag) of the lib on github and when it is updated and you want to use the newest version just change the version in your cmakelist.

That's way better because in case of breaking changes you don't want to have your production break and not build (once again I think mostly about enterprises here because they are the ones using development the most, people on their own don't represent as much as what enterprises do).

I've got an example of a school project where we had this problem.
We can use either raylib of irrlicht (the both allow to make 3D games, raylib is in C and irrlicht in C++) I personally used raylib with my group and the use master as a development version and the Findraylib.cmake that the school gave us was fetching master which has breaking change compared to the latest version (at the time of the project which is a couple of month ago) and master is also their development branch so once they had a cmakelist problem on master and everyone using raylib for the project couldn't build if they had to fetch the raylib (if they already had it in cache it could be OK) (so well yeah no dev version unless you truly need it) and so I changed it to go fetch the latest version available at the time and that allowed us to be sure to not have problems at the last run of the automated tests (which builds the project) and to not encounter breaking changes when we really don't need that.

**Comment by KOLANICH** [comment]
>Don't forget that it is a single header here and you think of development as development that you do on your own but there are a lot of cases (in enterprises) where they use older versions because updating the whole project (most of the times few 100k of lines of even more and updating everything isn't wanted by them which is why in C/C++ as Linux distribution package manager don't allow to install a specific version it might be better to have the lib in your project directly

My PR is should not disrupt this use case.

>That's way better because in case of breaking changes you don't want to have your production break and not build

No, for some cases it's worse. When something is incompatible to the latest version, it is clearly a bug. Of course maintainers may prefer not to fix it, but it is still a bug.

>and so I changed it to go fetch the latest version available at the time and that allowed us to be sure to not have problems at the last run of the automated tests

It's like hiding dirt behind a carpet. The dirt is still here, it is still dirt, but it is masked. The proper solution is to change the sources so they can be built against both versions, the bleeding edge `master` and the latest release. And to change the CI to test against both versions. And if needed, setup CI for building packages for the latest version of the dep and publishing it in the format that can be consumed by the package manager. Doing the things right is almost never the easiest way.

**Comment by tocola** [comment]
Thanks for your contribution and your explanations (I don't have many knowledge about CMake). I'm gonna merge it soon 👍

**Pull request merged**
